title: Solar Sprout
description: Film, Music, Games, Art & More by Shree Samavedhi
baseurl: ""
url: "https://solarsprout.online"

# Theme settings
# Using custom theme files instead of minima
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# GitHub Pages compatibility
# safe: false  # Commented out as GitHub Pages forces safe mode

# Navigation
header_pages:
  - pages/blog.md
  - pages/portfolio.md
  - pages/about.md

# Collections
collections:
  tags:
    output: true
    permalink: /tag/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /posts/:year/:month/:day/:title/
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"
  - scope:
      path: ""
    values:
      layout: "default"

# Build settings
markdown: kramdown
highlighter: rouge

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
