title: Solar Sprout
description: Animation, Games, Music, Art & More by Shree Samavedhi
baseurl: ""
url: "https://solarsprout.online"

# Theme settings
# Using custom theme files instead of minima
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation
header_pages:
  - blog.md
  - portfolio.md
  - about.md

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/
  tags:
    output: true
    permalink: /tag/:name/

defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"
  - scope:
      path: ""
    values:
      layout: "default"

# Build settings
markdown: kramdown
highlighter: rouge
