title: Solar Sprout
description: Film, Music, Games, Art & More by Shree Samavedhi
baseurl: ""
url: "https://solarsprout.online"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata

# GitHub Pages compatibility
repository: shreesamavedhi/solarsprout.online

# Navigation
header_pages:
  - pages/blog.md
  - pages/portfolio.md
  - pages/about.md
  - pages/shop.md

# Collections
collections:
  tags:
    output: true
    permalink: /tag/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /posts/:year/:month/:day/:title/
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"
  - scope:
      path: ""
    values:
      layout: "default"

# Additional build settings
highlighter: rouge

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
